title:              Louis Finegan
email:              louis.m.finegan@gmail.com
description:        Hello, My name is Louis. I am an Irish student of Mathematical Science at Maynooth University, Kildare Ireland. Throughout my studies I have encountered a variety of topics in pure/applied mathematics, statistics and mechanics. This website is where I share my exploration of those topics, connecting theory with real-world applications. 
author:             Louis Finegan
baseurl:            ""
url:                "https://louis-finegan.github.io"

# Social Profiles
twitter_username:   
github_username:    Louis-Finegan
facebook_username:  
instagram_username:  
linkedin_username:  louis-m-finegan-065202242

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge